/* ============================================================
   role.js — JobBored v2 PART 03 (The Dossier) + empty-state shelf
   ------------------------------------------------------------
   Owner:    Conductor (Phase 2 · flowing-page · role region)
   Renders:  <section data-region="role">
   Reads:    window.JobBoredDawn.data.getRoleViewModel(jobKey)
   State:    window.JobBoredFlowing.openRole
   Events:
     LISTENS  jb:role:opened  { jobKey }
              jb:role:closed
     EMITS    jb:pipeline:move  { jobKey, fromStage, toStage }
              jb:role:action    { action, jobKey }
              jb:role:note      { jobKey, body }
              (and re-triggers a smooth scroll to letter region)

   Activation: body.jb-v2 only. Off-flag: no-op.
   ============================================================ */

(function (root) {
  "use strict";

  var REGION_SELECTOR = '[data-region="role"]';
  var LETTER_REGION_SELECTOR = '[data-region="letter"]';
  var PIPELINE_REGION_SELECTOR = '[data-region="pipeline"]';

  var STAGE_LABELS = {
    "researching":  "Researching",
    "applied":      "Applied",
    "phone-screen": "Phone screen",
    "interviewing": "Interviewing",
    "offer":        "Offer",
  };
  var STAGE_ORDER = ["researching", "applied", "phone-screen", "interviewing", "offer"];

  function shouldRun() {
    return !!(document.body && document.body.classList && document.body.classList.contains("jb-v2"));
  }

  function getRegion() {
    return document.querySelector(REGION_SELECTOR);
  }

  function escapeHtml(s) {
    if (s == null) return "";
    return String(s)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

  function safeVm(jobKey) {
    var api = root.JobBoredDawn && root.JobBoredDawn.data;
    if (!api || typeof api.getRoleViewModel !== "function") return null;
    try { return api.getRoleViewModel(jobKey); }
    catch (e) {
      if (root.console && root.console.warn) root.console.warn("[role] getRoleViewModel threw", e);
      return null;
    }
  }

  function dispatch(name, detail) {
    if (typeof root.CustomEvent !== "function") return;
    try {
      var ev = new root.CustomEvent(name, { detail: detail || {}, bubbles: true });
      // Bridge in flowing-writes.js listens on `document`; chrome/region code
      // expects window. Dispatch on both so neither path misses the event.
      if (typeof document !== "undefined" && document.dispatchEvent) document.dispatchEvent(ev);
      root.dispatchEvent(ev);
    } catch (e) { /* */ }
  }

  function formatDate(iso) {
    if (!iso) return "";
    var t = Date.parse(iso);
    if (!Number.isFinite(t)) return iso;
    var d = new Date(t);
    var pad = function (n) { return n < 10 ? "0" + n : "" + n; };
    return d.getFullYear() + "-" + pad(d.getMonth() + 1) + "-" + pad(d.getDate());
  }

  /* -------------------- empty-state -------------------- */

  function renderEmpty(region) {
    region.innerHTML = '' +
      '<div class="jb-shelf">' +
        '<div class="jb-shelf__rule"></div>' +
        '<div class="jb-shelf__num">PART <em>03</em> · WAITING</div>' +
        '<h2 class="jb-shelf__title">Open a role to <em>read</em>.</h2>' +
        '<p class="jb-shelf__sub">Click any card in the pipeline above. The dossier and your tailored materials will unfold here.</p>' +
        '<div class="jb-shelf__hints">' +
          '<div class="jb-hint">' +
            '<div class="jb-hint__eyebrow">THE DOSSIER</div>' +
            '<h3 class="jb-hint__title">Company, JD, your notes, the people you\'ve talked to, and every fact on file.</h3>' +
            '<div class="jb-hint__desc">A long-form read. Replaces the old slide-out drawer.</div>' +
          '</div>' +
          '<div class="jb-hint">' +
            '<div class="jb-hint__eyebrow">APPLICATION MATERIALS</div>' +
            '<h3 class="jb-hint__title">Tailored resume + cover letter, generated by Hermes and reviewed here.</h3>' +
            '<div class="jb-hint__desc">Draft cover letter / Tailor resume request a fresh pass; new files appear in the dossier when ready.</div>' +
          '</div>' +
        '</div>' +
        '<button type="button" class="jb-shelf__cta" data-shelf-cta="pipeline">' +
          '<span>↑ Pick a role from the pipeline</span>' +
          '<span class="jb-shelf__cta-key">⌘K</span>' +
          '<span>to search</span>' +
        '</button>' +
      '</div>';

    // wire up clicks
    var cta = region.querySelector('[data-shelf-cta="pipeline"]');
    if (cta) {
      cta.addEventListener("click", function () {
        var pipeline = document.querySelector(PIPELINE_REGION_SELECTOR);
        if (pipeline) {
          var prefersReduced = root.matchMedia && root.matchMedia("(prefers-reduced-motion: reduce)").matches;
          try {
            pipeline.scrollIntoView({ behavior: prefersReduced ? "auto" : "smooth", block: "start" });
          } catch (e) { pipeline.scrollIntoView(); }
        }
        var pipelineApi = root.JobBoredPipeline;
        if (pipelineApi && typeof pipelineApi.focusSearch === "function") {
          root.setTimeout(function () {
            pipelineApi.focusSearch({ select: true });
          }, 80);
        }
      });
    }
  }

  /* -------------------- dossier — mirrors right-hand .detail-drawer -------------------- */

  function safeHref(href) {
    var s = String(href || "").trim();
    if (!s) return "";
    if (/^https?:|^mailto:/i.test(s)) return s;
    return "";
  }

  function renderDrawerHead(job) {
    var roleFacts = [];
    if (job.location)   roleFacts.push('<span class="role-fact role-fact--location">' + escapeHtml(job.location) + '</span>');
    if (job.salary)     roleFacts.push('<span class="role-fact role-fact--salary">' + escapeHtml(job.salary) + '</span>');
    if (job.employment) roleFacts.push('<span class="role-fact role-fact--employment">' + escapeHtml(job.employment) + '</span>');
    var factsHtml = roleFacts.length
      ? '<div class="role-facts role-facts--drawer">' + roleFacts.join("") + '</div>'
      : "";
    var companyHtml = job.company
      ? '<p class="detail-drawer__head-company">' + escapeHtml(job.company) + '</p>'
      : "";
    return '' +
      '<div class="detail-drawer__head">' +
        '<div class="detail-drawer__head-main">' +
          '<h2 class="detail-drawer__head-title">' + escapeHtml(job.role || "Untitled role") + '</h2>' +
          companyHtml +
          factsHtml +
        '</div>' +
        '<button type="button" class="detail-drawer__close" data-action="close-role" aria-label="Close">' +
          '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>' +
        '</button>' +
      '</div>';
  }

  function renderDrawerActions(job) {
    var coverBtn =
      '<button type="button" class="drawer-btn drawer-btn--cover" data-action="resume-cover">' +
        '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>' +
        ' Cover letter' +
      '</button>';
    var tailorBtn =
      '<button type="button" class="drawer-btn drawer-btn--tailor" data-action="resume-tailor">' +
        '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"/></svg>' +
        ' Tailor resume' +
      '</button>';
    var postingHref = "";
    if (job.links && job.links.length) {
      for (var i = 0; i < job.links.length; i++) {
        var h = safeHref(job.links[i] && job.links[i].href);
        if (h) { postingHref = h; break; }
      }
    }
    var viewBtn = postingHref
      ? '<a href="' + escapeHtml(postingHref) + '" target="_blank" rel="noopener" class="drawer-btn drawer-btn--view">' +
          '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>' +
          ' View posting' +
        '</a>'
      : "";
    return '<div class="detail-drawer__actions">' + coverBtn + tailorBtn + viewBtn + '</div>';
  }

  function renderAboutSection(job) {
    // Build the same `<details class="drawer-about">` shape the drawer uses.
    // Hook line — companyTagline or first JD bullet/body.
    var hook = "";
    if (job.companyTagline) hook = job.companyTagline;
    else if (job.jdSections && job.jdSections.length) {
      var s0 = job.jdSections[0];
      hook = s0.body || (s0.bullets && s0.bullets[0]) || "";
    } else if (job.jdSnippet) {
      hook = job.jdSnippet;
    }
    var hookHtml = hook ? '<p class="drawer-hook">' + escapeHtml(hook) + '</p>' : "";

    // AI summary — the dossier VM doesn't expose enrichment; fall back to longer JD body.
    var aiText = "";
    if (job.jdSections && job.jdSections.length) {
      var first = job.jdSections[0];
      if (first.body && first.body !== hook) aiText = first.body;
    }
    var aiHtml = aiText
      ? '<div class="drawer-ai-section"><span class="drawer-section__label">AI Summary</span><p class="drawer-ai-text">' + escapeHtml(aiText) + '</p></div>'
      : "";

    // Tags
    var tags = Array.isArray(job.tags) ? job.tags.filter(Boolean) : [];
    var tagsHtml = tags.length
      ? '<div class="drawer-ai-section"><span class="drawer-section__label">Tags &amp; skills</span><div class="card-tags card-skills-tags">' +
          tags.map(function (t) { return '<span class="skill-chip">' + escapeHtml(t) + '</span>'; }).join("") +
        '</div></div>'
      : "";

    // Source
    var srcHtml = job.source
      ? '<p class="card-peek__source">via ' + escapeHtml(job.source) + '</p>'
      : "";

    var bodyContent = aiHtml + tagsHtml + srcHtml;
    if (!hookHtml && !bodyContent) return "";
    if (!bodyContent) return hookHtml;

    return '<details class="drawer-about" open>' +
      '<summary class="drawer-about__toggle">About this role</summary>' +
      '<div class="drawer-about__body">' + hookHtml + bodyContent + '</div>' +
    '</details>';
  }

  function renderStructuredFromJd(job) {
    // Reuse the drawer's posting-struct shells for JD sections after the first one.
    if (!job.jdSections || job.jdSections.length <= 1) return "";
    var rest = job.jdSections.slice(1);
    return rest.map(function (section) {
      if (!section) return "";
      var label = section.heading || "Posting";
      var items = Array.isArray(section.bullets) ? section.bullets.filter(Boolean) : [];
      var bodyP = section.body ? '<p class="drawer-ai-text">' + escapeHtml(section.body) + '</p>' : "";
      var bulletsHtml = items.length
        ? '<ul class="posting-req-list">' + items.map(function (b) { return '<li>' + escapeHtml(b) + '</li>'; }).join("") + '</ul>'
        : "";
      if (!bodyP && !bulletsHtml) return "";
      return '<div class="posting-struct">' +
        '<span class="posting-snippet-label">' + escapeHtml(label) + '</span>' +
        bodyP + bulletsHtml +
      '</div>';
    }).join("");
  }

  function renderTalkingPoints(job) {
    // Surface bullets from the first JD section as "Talking points" (drawer parity).
    if (!job.jdSections || !job.jdSections.length) return "";
    var first = job.jdSections[0];
    var bullets = Array.isArray(first.bullets) ? first.bullets.filter(Boolean) : [];
    if (!bullets.length) return "";
    return '<div class="drawer-ai-section">' +
      '<span class="drawer-section__label">' +
        '<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg> Talking points' +
      '</span>' +
      '<ul class="talking-points-list">' + bullets.map(function (b) { return '<li>' + escapeHtml(b) + '</li>'; }).join("") + '</ul>' +
    '</div>';
  }

  function renderProps(job) {
    var stageKey = job.stage || "";
    var stageOptions = STAGE_ORDER.map(function (s) {
      var sel = s === stageKey;
      return '<option value="' + escapeHtml(s) + '"' + (sel ? " selected" : "") + '>' + escapeHtml(STAGE_LABELS[s] || s) + '</option>';
    }).join("");
    if (!stageKey) {
      stageOptions = '<option value="" selected>—</option>' + stageOptions;
    }

    var appliedRow = job.appliedAt
      ? '<div class="drawer-prop">' +
          '<svg class="drawer-prop__icon" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 2L11 13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>' +
          '<span class="drawer-prop__key">Applied</span>' +
          '<span class="drawer-prop__val drawer-prop__val--static">' + escapeHtml(formatDate(job.appliedAt)) + '</span>' +
        '</div>'
      : "";

    var deadlineRow = "";
    if (job.deadline && job.deadline.dueDate) {
      var dueText = formatDate(job.deadline.dueDate);
      var daysText = Number.isFinite(job.deadline.daysUntil)
        ? (job.deadline.daysUntil >= 0 ? "in " + job.deadline.daysUntil + "d" : Math.abs(job.deadline.daysUntil) + "d ago")
        : "";
      deadlineRow = '<div class="drawer-prop">' +
        '<svg class="drawer-prop__icon" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>' +
        '<span class="drawer-prop__key">Deadline</span>' +
        '<span class="drawer-prop__val drawer-prop__val--static">' + escapeHtml(dueText + (daysText ? " · " + daysText : "")) + '</span>' +
      '</div>';
    }

    var fitRow = (job.fitScore != null)
      ? '<div class="drawer-prop">' +
          '<svg class="drawer-prop__icon" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>' +
          '<span class="drawer-prop__key">Fit</span>' +
          '<span class="drawer-prop__val drawer-prop__val--static">' + escapeHtml(String(job.fitScore)) + '</span>' +
        '</div>'
      : "";

    var sourceRow = job.source
      ? '<div class="drawer-prop">' +
          '<svg class="drawer-prop__icon" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>' +
          '<span class="drawer-prop__key">Source</span>' +
          '<span class="drawer-prop__val drawer-prop__val--static">' + escapeHtml(job.source) + '</span>' +
        '</div>'
      : "";

    return '<div class="drawer-props">' +
      '<div class="drawer-prop">' +
        '<svg class="drawer-prop__icon" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/></svg>' +
        '<span class="drawer-prop__key">Stage</span>' +
        '<select class="drawer-prop__val" data-action="stage-select">' + stageOptions + '</select>' +
      '</div>' +
      fitRow +
      deadlineRow +
      appliedRow +
      sourceRow +
    '</div>';
  }

  function renderNotesBlock(job) {
    var body = (job.notes && job.notes.body) ? job.notes.body : "";
    return '<div class="drawer-notes">' +
      '<label class="drawer-section__label" for="jb-dossier-notes">Notes</label>' +
      '<textarea id="jb-dossier-notes" class="drawer-notes__input" data-action="notes" placeholder="Interview prep, recruiter name, next steps…">' + escapeHtml(body) + '</textarea>' +
    '</div>';
  }

  function renderDossier(region, vm) {
    var job = (vm && vm.job) || {};

    region.innerHTML = '' +
      '<div class="jb-role-divider">' +
        '<div class="jb-role-divider__rule"></div>' +
        '<div class="jb-role-divider__inner">' +
          '<div>' +
            '<div class="jb-role-divider__num">PART 03 · NOW READING</div>' +
            '<div class="jb-role-divider__title">The <em>dossier</em></div>' +
          '</div>' +
        '</div>' +
      '</div>' +
      '<div class="dossier">' +
        '<article class="brief" data-mount="brief"></article>' +
      '</div>';

    var briefMount = region.querySelector('[data-mount="brief"]');
    if (briefMount && root.JobBoredDossierBrief && typeof root.JobBoredDossierBrief.renderBrief === "function") {
      root.JobBoredDossierBrief.renderBrief(briefMount, vm);
    }

    wireDossier(region, job);
  }

  function getCurrentJobKey() {
    return root.JobBoredFlowing
      && root.JobBoredFlowing.openRole
      && root.JobBoredFlowing.openRole.get();
  }

  function wireRegionClickOnce(region) {
    if (region.__jbRoleClickWired) return;
    region.__jbRoleClickWired = true;

    function closeRole() {
      if (root.JobBoredFlowing && root.JobBoredFlowing.openRole) root.JobBoredFlowing.openRole.clear();
    }

    region.addEventListener("click", function (e) {
      var t = e.target;
      while (t && t !== region) {
        var action = t.getAttribute && t.getAttribute("data-action");
        if (action === "close-role") { closeRole(); return; }
        if (action === "resume-cover" || action === "resume-tailor") {
          /* Materials-first pivot (2026-05-27): the dossier CTAs now
             trigger a Hermes drafting request via the materials API
             (handled in role-materials.js). The legacy in-browser
             modal flow (openDraftNotesModal → Gemini/OpenAI in the
             browser) is no longer the default. */
          dispatch("jb:role:action", { action: action, jobKey: getCurrentJobKey() });
          return;
        }
        t = t.parentNode;
      }
    });
  }

  function wireDossier(region, job) {
    var jobKey = job.jobKey || getCurrentJobKey();

    wireRegionClickOnce(region);

    // Stage select — dispatch pipeline move on change.
    var stageSel = region.querySelector('[data-action="stage-select"]');
    if (stageSel) {
      stageSel.addEventListener("change", function () {
        var toStage = stageSel.value;
        if (!toStage) return;
        dispatch("jb:pipeline:move", { jobKey: jobKey, fromStage: job.stage || null, toStage: toStage });
      });
    }

    // Notes textarea — persist on blur.
    var notesTa = region.querySelector('[data-action="notes"]');
    if (notesTa) {
      notesTa.addEventListener("blur", function () {
        var body = notesTa.value.trim();
        dispatch("jb:role:note", { jobKey: jobKey, body: body });
      });
    }
  }

  /* -------------------- top-level render -------------------- */

  function renderForKey(jobKey) {
    if (!shouldRun()) return;
    var region = getRegion();
    if (!region) return;
    if (!jobKey) {
      renderEmpty(region);
      return;
    }
    var vm = safeVm(jobKey);
    if (!vm || !vm.job || (!vm.job.role && !vm.job.company)) {
      // unknown key — fall back to empty state but keep hash so reload still tries.
      renderEmpty(region);
      return;
    }
    renderDossier(region, vm);
  }

  function onOpened(e) {
    var key = e && e.detail && e.detail.jobKey;
    renderForKey(key);
  }
  function onClosed() {
    renderForKey(null);
  }

  function rerenderOpenRole() {
    var key = root.JobBoredFlowing
      && root.JobBoredFlowing.openRole
      && root.JobBoredFlowing.openRole.get();
    if (key) renderForKey(key);
  }

  function init() {
    if (!shouldRun()) {
      // Watch for flag flip
      if (typeof root.MutationObserver === "function" && document.body) {
        var mo = new root.MutationObserver(function () { if (shouldRun()) { init(); mo.disconnect(); } });
        mo.observe(document.body, { attributes: true, attributeFilter: ["class"] });
      }
      return;
    }
    var key = root.JobBoredFlowing && root.JobBoredFlowing.openRole && root.JobBoredFlowing.openRole.get();
    renderForKey(key);
    root.addEventListener("jb:role:opened", onOpened);
    root.addEventListener("jb:role:closed", onClosed);
    /* Cached enrichments are restored when app.js renders the Pipeline.
       If a role was already open (for example after a hard reload with a
       #role hash), re-read the freshly-rendered card data-* attrs so the
       Dossier does not stay on its pre-hydration basic view. */
    if (document && document.addEventListener) {
      document.addEventListener("jb:pipeline:rendered", rerenderOpenRole);
    }
    /* When app.js finishes scrape + Gemini enrichment for a role, the
       kanban-card's data-* attributes are refreshed; re-render the
       Dossier so it picks up the new AI fields. */
    root.addEventListener("jb:role:enriched", function (e) {
      var k = e && e.detail && e.detail.jobKey;
      var openKey = root.JobBoredFlowing
        && root.JobBoredFlowing.openRole
        && root.JobBoredFlowing.openRole.get();
      if (k != null && String(k) === String(openKey)) {
        renderForKey(openKey);
      }
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }

  // public surface (mostly for tests)
  root.JobBoredFlowing = root.JobBoredFlowing || {};
  root.JobBoredFlowing.role = {
    renderForKey: renderForKey,
  };
})(typeof window !== "undefined" ? window : this);
