import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, it } from "node:test";

import {
  generateWebhookSecret,
  parseEnvFile,
  WEBHOOK_SECRET_ENV_KEY,
} from "../scripts/bootstrap-local-discovery.mjs";

/**
 * The bootstrap script's `resolveWebhookSecret` reads from a fixed file path
 * (`integrations/browser-use-discovery/.env`), which makes it awkward to test
 * directly without polluting the real repo .env. So we test the *building
 * blocks* (parseEnvFile + generateWebhookSecret) plus a faithful re-implement
 * of the resolution priority that runs against a temp directory. The cost is
 * that the re-implementation has to be kept in sync with the script — but the
 * priority order itself is the contract worth pinning down.
 */

describe("bootstrap webhook secret resolver", () => {
  describe("parseEnvFile", () => {
    it("parses bare KEY=VALUE lines", () => {
      const out = parseEnvFile("FOO=bar\nBAZ=qux");
      assert.equal(out.FOO, "bar");
      assert.equal(out.BAZ, "qux");
    });

    it("ignores blank lines and # comments", () => {
      const out = parseEnvFile(
        ["# top comment", "", "FOO=bar", "  ", "# another", "BAZ=qux"].join("\n"),
      );
      assert.equal(Object.keys(out).length, 2);
      assert.equal(out.FOO, "bar");
      assert.equal(out.BAZ, "qux");
    });

    it("strips matching surrounding double or single quotes", () => {
      const out = parseEnvFile(
        ['DOUBLE="hello world"', "SINGLE='also fine'", "RAW=plain"].join("\n"),
      );
      assert.equal(out.DOUBLE, "hello world");
      assert.equal(out.SINGLE, "also fine");
      assert.equal(out.RAW, "plain");
    });

    it("does not crash on malformed lines", () => {
      const out = parseEnvFile("=NOKEY\njust-a-line\nFOO=bar");
      assert.equal(out.FOO, "bar");
      assert.ok(!Object.prototype.hasOwnProperty.call(out, ""));
    });

    it("returns an empty object for non-string input", () => {
      assert.deepEqual(parseEnvFile(null), {});
      assert.deepEqual(parseEnvFile(undefined), {});
      assert.deepEqual(parseEnvFile(123), {});
    });
  });

  describe("generateWebhookSecret", () => {
    it("returns 64 hex chars (32 random bytes)", () => {
      const secret = generateWebhookSecret();
      assert.match(secret, /^[0-9a-f]{64}$/);
    });

    it("returns a unique value on each call", () => {
      const a = generateWebhookSecret();
      const b = generateWebhookSecret();
      assert.notEqual(a, b);
    });
  });

  describe("resolution priority (process env > .env file > generate)", () => {
    /**
     * Faithful local reimplementation of resolveWebhookSecret() that runs
     * against an injectable env-file path. If the production resolver's
     * priority order ever changes, this test should fail and force the
     * change to be deliberate.
     */
    function resolveSecret({ envObject, envFilePath }) {
      const fromProcess = String(envObject[WEBHOOK_SECRET_ENV_KEY] || "").trim();
      if (fromProcess) {
        return { secret: fromProcess, source: "process_env", wrote: false };
      }
      let fromFile = "";
      if (existsSync(envFilePath)) {
        const text = readFileSync(envFilePath, "utf8");
        const parsed = parseEnvFile(text);
        if (parsed[WEBHOOK_SECRET_ENV_KEY]) {
          fromFile = String(parsed[WEBHOOK_SECRET_ENV_KEY]).trim();
        }
      }
      if (fromFile) {
        return { secret: fromFile, source: "env_file", wrote: false };
      }
      const generated = generateWebhookSecret();
      const banner =
        "# integrations/browser-use-discovery/.env\n# Generated by `npm run discovery:bootstrap-local`. Gitignored.\n";
      const line = `${WEBHOOK_SECRET_ENV_KEY}=${generated}\n`;
      writeFileSync(envFilePath, `${banner}\n${line}`, "utf8");
      return { secret: generated, source: "generated", wrote: true };
    }

    let tempDir;
    let envFilePath;

    beforeEach(() => {
      tempDir = mkdtempSync(join(tmpdir(), "boot-secret-"));
      envFilePath = join(tempDir, ".env");
    });

    afterEach(() => {
      try {
        rmSync(tempDir, { recursive: true, force: true });
      } catch (_) {
        // best-effort
      }
    });

    it("reuses process.env value without touching the .env file", () => {
      const r = resolveSecret({
        envObject: { [WEBHOOK_SECRET_ENV_KEY]: "from-process" },
        envFilePath,
      });
      assert.equal(r.secret, "from-process");
      assert.equal(r.source, "process_env");
      assert.equal(r.wrote, false);
      assert.equal(existsSync(envFilePath), false);
    });

    it("falls back to .env file when process.env is empty", () => {
      writeFileSync(
        envFilePath,
        `${WEBHOOK_SECRET_ENV_KEY}=from-env-file\nOTHER=ignored\n`,
        "utf8",
      );
      const r = resolveSecret({ envObject: {}, envFilePath });
      assert.equal(r.secret, "from-env-file");
      assert.equal(r.source, "env_file");
      assert.equal(r.wrote, false);
    });

    it("generates and writes a new secret when neither source has one", () => {
      const r = resolveSecret({ envObject: {}, envFilePath });
      assert.equal(r.source, "generated");
      assert.equal(r.wrote, true);
      assert.match(r.secret, /^[0-9a-f]{64}$/);
      const written = readFileSync(envFilePath, "utf8");
      assert.ok(
        written.includes(`${WEBHOOK_SECRET_ENV_KEY}=${r.secret}`),
        "generated secret must be persisted to the env file",
      );
    });

    it("subsequent reads after generation return the persisted value", () => {
      const first = resolveSecret({ envObject: {}, envFilePath });
      const second = resolveSecret({ envObject: {}, envFilePath });
      assert.equal(second.source, "env_file");
      assert.equal(second.secret, first.secret);
      assert.equal(second.wrote, false);
    });

    it("trims whitespace around values from .env", () => {
      writeFileSync(envFilePath, `${WEBHOOK_SECRET_ENV_KEY}=  padded  \n`, "utf8");
      const r = resolveSecret({ envObject: {}, envFilePath });
      assert.equal(r.secret, "padded");
    });

    it("treats whitespace-only process.env as absent", () => {
      writeFileSync(envFilePath, `${WEBHOOK_SECRET_ENV_KEY}=from-file\n`, "utf8");
      const r = resolveSecret({
        envObject: { [WEBHOOK_SECRET_ENV_KEY]: "   " },
        envFilePath,
      });
      assert.equal(r.source, "env_file");
      assert.equal(r.secret, "from-file");
    });
  });
});
